### PR TITLE
Add highlighting to variable view and improve perf

### PR DESCRIPTION
**Pull request by tecosaur**
Use type predicates to select an appropriate face for viewing values, and use type information to also use quicker type-to-string conversion when possible. It's worth noting that after this patch I find scrolling through candidates noticeably smoother.

### Demo

image

### Changes to note

- Keymaps are now shown as `<keymap>` because the preview of the first few chars of the list representation is (a) inconsistent with the variable view for keymaps, (b) too short to possibly be useful.
- Strings are also a bit different now as text properties are not shown in the value preview. However, similarly, I find the short amount of space available to preview properetized strings almost always insufficient to be of help, and the value view is always a better option, so I think this is a beneficial change.

##### Ivy (for reference)
image

##### Marginalia + this patch

image

##### The variable view

image

### CODE REVIEW

**Comment by elken** [comment]
I've also been testing these changes and there is a _noticable_ performance improvement outside of the aesthetic one.

**Comment by tecosaur** [comment]
Well that was quick :stuck_out_tongue:

**Comment by minad** [comment]
Great, thank you! I will make some stylistic changes, but the change is a great idea. Do you have more visual improvements? Regarding the performance issues you mentioned - you are probably referring to the fact that Marginalia does ~vertico-count unnecessary annotation recomputations for each redisplay when scrolling? Maybe I should introduce caching, but note that the caching will not help much when filtering.

**Comment by minad** [comment]
I have never compared Ivy-rich and Marginalia side-by-side, so we may be missing some polishing. I hope it is not too bad :)

**Comment by tecosaur** [comment]
Glad you like it :slightly_smiling_face:. There are more visual improvements that are being discussed in the Doom discord, but currently they rely on other `doom-themes` for colour blending, and `diredfl` for file attribute faces. There's probably potential for _something_ though. Here's a sample:

image

I've also been doing a bit of a deeper dive into the performance, As an example, here's one of my screenshots from the discord:

image

**Comment by minad** [comment]
I converted to pcase https://github.com/minad/marginalia/commit/444c5d10b24a06bba048fc49c9709270edcd38df

Any particular reason why you avoided pcase? I like it very much for such use cases.

**Comment by minad** [comment]
The file annotator improvements look pretty, I would like to have them here. This means we have to replicate a bunch of diredfl face definitions here. It is a bit unfortunate for the theme authors though.

**Comment by tecosaur** [comment]
> Any particular reason why you avoided pcase? I like it very much for such use cases.

Basically, I didn't think the difference in form was that significant, but a bunch of spurious `(let nil ...)`-type statements are generated by the macro and basically generates a messier `(cond ...)`. It probably has no impact on performance, but I thought why not just use `cond` then.

> The file annotator improvements look pretty, I would like to have them here.

I'd rather upstream nice things than have them in my config or Doom-specific, there's just a bit of thinking needed about approach it.

Oh, an aside on string formatting: I noticed you switch back to `print1-to-string`. I'm curious what the motivation behind that is?
The only difference I see is instead of
image
I now see
image

Which isn't consistent with the variable view or how those characters appear in buffers.

**Comment by minad** [comment]
> Basically, I didn't think the difference in form was that significant, but a bunch of spurious (let nil ...)-type statements are generated by the macro and basically generates a messier (cond ...). It probably has no impact on performance, but I thought why not just use cond then.

Okay, sure. It is just a stylistic change. I like that the code is indented less deeply ;)

> I'd rather upstream nice things than have them in my config or Doom-specific, there's just a bit of thinking needed about approach it.

Agree.

> Oh, an aside on string formatting: I noticed you switch back to print1-to-string. I'm curious what the motivation behind that is?

Okay, I can switch this back again. Actually I am worried that using the string as is will mess up the Marginalia display badly. This should not happen when going through the quotation of `prin1-to-string`. But maybe my worries are unfounded. Still, I would prefer if we adjust `prin1-to-string` such that it gives the better result. The problem is probably `print-escape-control-characters` etc.

**Comment by tecosaur** [comment]
> The problem is probably `print-escape-control-characters` etc.

I can confirm that leaving out `print-escape-control-characters` / setting it to `nil` makes the control characters display "normally".

> Actually I am worried that using the string as is will mess up the Marginalia display badly

Ah, I see. I appreciate this concern. Correct me if I'm wrong, but since the string is truncated is there anything to watch out for beyond characters that create a line break?

**Comment by minad** [comment]
Thanks for the profile btw. I also profiled again and Marginalia is indeed a major performance offender. I added annotator caching to mitigate this (https://github.com/minad/marginalia/commit/ee24a2390fb472a549224ae4a084958b4132ea82), but I am not entirely sure if Marginalia is the right place to do this. I could also add caching to Vertico - but it seems to me that Marginalia are the only costly annotators and it mostly replaces the default annotators.

**Comment by minad** [comment]
> Correct me if I'm wrong, but since the string is truncated is there anything to watch out for beyond characters that create a line break?

There are also unicode control characters which change the text direction and maybe other things. I don't actually know - therefore prin1-to-string is the safer bet :shrug:

**Comment by tecosaur** [comment]
> Thanks for the profile btw. I also profiled again and Marginalia is indeed a major performance offender. I added annotator caching to mitigate this (ee24a23), but I am not entirely sure if Marginalia is the right place to do this. I could also add caching to Vertico - but it seems to me that Marginalia provides the only costly annotators and it mostly replaces the default annotators.

I scrolled through a file selector for ~20 files for a few seconds and the annotation functions were called a few thousand times, so  I think some caching is absolutely warranted. Would caching on the vertico side make sense? It's probably worth noting that time taken by `vertico--exhibit` seems usually evenly split between `vertico--affixate` and `vertico--resize-window`.

image

> There are also unicode control characters which change the text direction

Oh yes there are, aren't there! Hmmm, is `prin1-to-string` actually enough to deal with those?

**Comment by minad** [comment]
> I scrolled through a find-file prompt for ~20 files for a few seconds and the annotation functions were called a few thousand times, so I think some caching is absolutely warranted.

Please try the caching commit. This should fix the issue.

> prin1-to-string actually enough to deal with those?

Yes with the control character escaping.

Regarding the diredfl faces - what about introducing a marginalia-file-face-alist, with keys size, exec, read, write etc bound to standard font lock faces. Then the user can redirect to diredfl faces in the config. This reduces the amount of work for themes.

**Comment by tecosaur** [comment]
> Please try the caching commit. This should fix the issue.

I've just pulled and it's noticeably better without me doing any actual profiling. Scrolling through lists may not be something I do much, but I feel like it's something that shouldn't have hickups so it's great to see the improvement :smiley:.

> Yes with the control character escaping.

Oh good. I did a perf test and it only doubles the time taken to format a string, which is better than what I expected.

> Regarding the diredfl faces - what about introducing a marginalia-file-face-alist, with keys size, exec, read, write etc bound to standard font lock faces? Then the user can redirect to diredfl faces in the config. This reduces the amount of work for themes.

On a first read this seems quite sensible to me :+1:. Would you like me to prepare a patch?

**Comment by minad** [comment]
> On a first read this seems quite sensible to me 👍. Would you like me to prepare a patch?

Yes, please prepare a patch. We can fix the face situation later on.

There are these options:

1. Replicate diredfl faces
2. Dynamically detect diredfl faces, use them or use font-lock instead
3. Use an alist indirection where the user can configure the faces

All solution have their pros and cons. Ping @protesilaos for an opinion.

**Comment by tecosaur** [comment]
> Yes, please prepare a patch. We can fix the face situation later on.

Sure, expect another PR shortly :slightly_smiling_face:.

I'll just pick one of the options for now so the rest of the code can be put into a PR or public viewing.

**Comment by tecosaur** [comment]
Oh, if you'd like I'll also include the logic that hides the user/group if it's the current user/group.

**Comment by protesilaos** [comment]
On 2021-07-26, 02:22 -0700, Daniel Mendler ***@***.***> wrote:

>> On a first read this seems quite sensible to me 👍. Would you like me
>> to prepare a patch?
>
> Yes, please prepare a patch. We can fix the face situation later on.
>
> There are these options:
>
> 1. Replicate diredfl faces
> 2. Dynamically detect diredfl faces, use them or use font-lock instead
> 3. Use an alist indirection where the user can configure the faces
>
> All solution have their pros and cons. Ping @protesilaos for an opinion.

Thanks for the ping and for those improvements :)

Inheriting from font-lock or such basic faces is the best default, even
though it may not always look great.

Note that if you plan to detect diredfl faces, you might also want to
extend that to dired+ (from whence those faces come from).  Granted,
that package is not on M?ELPA but I have seen people using it.

Here they are, in case you need them:

| diredfl                        | dired+                        |
|--------------------------------+-------------------------------|
| diredfl-autofile-name          | diredp-autofile-name          |
| diredfl-compressed-file-name   | diredp-compressed-file-name   |
| diredfl-compressed-file-suffix | diredp-compressed-file-suffix |
| diredfl-date-time              | diredp-date-time              |
| diredfl-deletion               | diredp-deletion               |
| diredfl-deletion-file-name     | diredp-deletion-file-name     |
| diredfl-dir-heading            | diredp-dir-heading            |
| diredfl-dir-name               | diredp-dir-name               |
| diredfl-dir-priv               | diredp-dir-priv               |
| diredfl-exec-priv              | diredp-exec-priv              |
| diredfl-executable-tag         | diredp-executable-tag         |
| diredfl-file-name              | diredp-file-name              |
| diredfl-file-suffix            | diredp-file-suffix            |
| diredfl-flag-mark              | diredp-flag-mark              |
| diredfl-flag-mark-line         | diredp-flag-mark-line         |
| diredfl-ignored-file-name      | diredp-ignored-file-name      |
| diredfl-link-priv              | diredp-link-priv              |
| diredfl-no-priv                | diredp-no-priv                |
| diredfl-number                 | diredp-number                 |
| diredfl-other-priv             | diredp-other-priv             |
| diredfl-rare-priv              | diredp-rare-priv              |
| diredfl-read-priv              | diredp-read-priv              |
| diredfl-symlink                | diredp-symlink                |
| diredfl-tagged-autofile-name   | diredp-tagged-autofile-name   |
| diredfl-write-priv             | diredp-write-priv             |

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by tecosaur** [comment]
I think it would be good if this works without `diredfl` / `dired+` so for now at least I'm just creating new faces. One could always add something like "if diredfl present, modify faces to just `:inherit` from the diredfl faces".

**Comment by minad** [comment]
@protesilaos 

> Inheriting from font-lock or such basic faces is the best default, even
though it may not always look great.

Yes, 1. is the most idiomatic, most configurable and simplest solution. Only disadvantage is the extra work for the theme authors, but this is probably better than pushing the work to the end users as in 3.

Auto detection is something I would like to avoid simply for the magic it introduces. But it would surely be the most convenient out of the box solution.

@tecosaur 

> I think it would be good if this works without diredfl / dired+ so for now at least I'm just creating new faces. One could always add something like "if diredfl present, modify faces to just :inherit from the diredfl faces".

Okay, I agree. Let's go with extra faces without any special dired+/diredfl integration.

**Comment by tecosaur** [comment]
*Ideally,* I think it would be great if diredfl's highlighting was merged into dired (seems like a good idea to me), as a side-effect we'd then have base Emacs faces to use for this.

**Comment by tecosaur** [comment]
Oh, since this seems to have become a bit of a general chat (poke me if I'm going too off-topic), @minad I have a bit of a gripe with the use of `(italic shadow)` as the default `marginalia-documentation` face. Surely `font-lock-doc-face` is the ideal face to inherit from?

**Comment by minad** [comment]
> Oh, since this seems to have become a bit of a general chat (poke me if I'm going too off-topic)

I will come to the discord, then we can chat more easily.

**Comment by eval-exec** [comment]
> > Thanks for the profile btw. I also profiled again and Marginalia is indeed a major performance offender. I added annotator caching to mitigate this ([ee24a23](https://github.com/minad/marginalia/commit/ee24a2390fb472a549224ae4a084958b4132ea82)), but I am not entirely sure if Marginalia is the right place to do this. I could also add caching to Vertico - but it seems to me that Marginalia provides the only costly annotators and it mostly replaces the default annotators.
> 
> I scrolled through a `find-file` prompt for ~20 files for a few seconds and the annotation functions were called a few thousand times, so I think some caching is absolutely warranted. Would caching on the vertico side make sense? It's probably worth noting that time taken by `vertico--exhibit` seems usually evenly split between `vertico--affixate` and `vertico--resize-window`.
> 
> image
> 
> > There are also unicode control characters which change the text direction
> 
> Oh yes there are, aren't there! Hmmm, is `prin1-to-string` actually enough to deal with those?

Hi, how did you create the image performance results?

**Pull request merged**
