### PR TITLE
Avoid annotations for host and remote path completions

### PR DESCRIPTION
**Pull request by clemera**
As discussed in https://github.com/raxod502/selectrum/issues/487

### CODE REVIEW

**Comment by clemera** [comment]
Not sure about interaction with marginalia/embark, maybe it can't be assumed the annotator is retrieved from the minibuffer?

**Comment by minad** [comment]
I don't want the patch in this form. Can you filter instead directly in the file annotator? And maybe only filter out the file-attributes call. Instead the annotators should show `*remote*` for example.

**Comment by minad** [comment]
What about providing two file annotator a instead. The current one which directly shows the file information and an additional annotator which filters the tramp files and shows `*remote*` for those and delegates to the usual annotator in the usual cases.

**Comment by clemera** [comment]
This fixes the problem for now can we do any improvements later on?

**Comment by clemera** [comment]
You can of course do it better right away but unfortunately I don't have any more time for it now, maybe in the evening.

**Comment by minad** [comment]
No, I won't merge half baked changes. I never do. Sorry. Take a look at #61 for a better approach.

**Comment by minad** [comment]
Closed in favor of #61.

**Comment by clemera** [comment]
Most things are half baked as you always extend programs later on ;)

**Pull request closed without merging**
