### PR TITLE
Revise marginalia faces

### PR DESCRIPTION
**Pull request by minad**
@protesilaos What do you think about these changes? Marginalia defines many faces now, maybe some of them should be unified or even be split further. If you have time to review, I appreciate it.

cc @tecosaur You may want to wait a bit with other theme updates until the Marginalia face situation is sorted out.

### CODE REVIEW

**Comment by protesilaos** [comment]
> @protesilaos What do you think about these changes? Marginalia defines many faces now, maybe some of them should be unified or even be split further. If you have time to review, I appreciate it.

I think [my point from #91](https://github.com/minad/marginalia/pull/91#issuecomment-886800952) is covered.  Thanks!

With regard to splitting them further, I think it is not necessary at this point.  Or, at least, I do not see an immediate need for such an exercise.

As for unifying some of them, you already have a template there with inheriting from `marginalia-number` or `marginalia-key`.  My take here is that we need to look into the specifics: I need more time to have a sense of the full picture.  For now, I would prefer to leave them as they are.  For instance, a MELPA version number is like `20210726.12345`, whereas a number value can be just a single digit.  For the latter case, we probably want a more pronounced colour.

**Comment by tecosaur** [comment]
Just 2c from me: I'm not convinced as to the value in introducing faces like `marginalia-function`. To me using the face `emacs-lisp-mode` will use for functions, for highlighting elisp functions is perfect. I suppose it doesn't hurt though.

**Comment by minad** [comment]
@protesilaos 

> As for unifying some of them, you already have a template there with inheriting from marginalia-number or marginalia-key. My take here is that we need to look into the specifics: I need more time to have a sense of the full picture. For now, I would prefer to leave them as they are. For instance, a MELPA version number is like 20210726.12345, whereas a number value can be just a single digit. For the latter case, we probably want a more pronounced colour.

The status is this currently:

* marginalia-number: General numeric values
* marginalia-version: Version numbers
* marginalia-key: Keybindings

**Comment by minad** [comment]
@tecosaur It seems to me that the two faces marginalia-string and marginalia-function are not really necessary. At this point we mostly add the faces for consistency. In total we define 32 semantic faces, having these two more does not hurt.

**Comment by protesilaos** [comment]
> The status is this currently:
> 
> + marginalia-number: General numeric values
> + marginalia-version: Version numbers
> + marginalia-key: Keybindings

Very well!  I think keeping them separate is safer, as it gives us more
flexibility.

Will update things on my end right away

**Comment by minad** [comment]
Thank you again, Prot!

**Comment by protesilaos** [comment]
You are welcome!

**Comment by tecosaur** [comment]
This line looks a bit suspicious

https://github.com/minad/marginalia/blob/b812925992c78bf5c1ab199af9b9149dc6ce210c/marginalia.el#L587

context:

https://github.com/minad/marginalia/blob/b812925992c78bf5c1ab199af9b9149dc6ce210c/marginalia.el#L584-L588

**Comment by minad** [comment]
Thanks, fixed. No idea how that happened.

**Comment by protesilaos** [comment]
I was just about to say the same.

**Pull request merged**
