### PR TITLE
Avoid annotations for host and remote path completions

### PR DESCRIPTION
**Pull request by clemera**
I have proceeded the way you went with #61. Maybe what annotation are shown for remote files shown should be configurable?

### CODE REVIEW

**Comment by minad** [comment]
I will take a look at this soon. Which information could be shown for remote files such that the slowdown is acceptable?

**Comment by clemera** [comment]
I mainly thought about not showing any info at all ;)

**Comment by minad** [comment]
Substitute-in-filename should also be used on the result returned by marginalia--full-candidate?

**Comment by clemera** [comment]
I don't know, `completion-boundaries` takes care of input with shadowed paths and the annotations work without it.

**Comment by clemera** [comment]
Is there anything left I should do?

**Comment by clemera** [comment]
Please let me know, I can surely add `substitute-in-filename` if you want it.

**Comment by minad** [comment]
I merged it

**Comment by clemera** [comment]
Why did you remove `substitute-in-file-name`?

**Comment by clemera** [comment]
Ah I see you match on both the cand and the minibuffer contents.

**Comment by clemera** [comment]
But it still doesn't seem to work with shadowed paths?

**Comment by minad** [comment]
> Why did you remove substitute-in-file-name?

It does not seem to make sense. I simply match on the `/protocol:` prefix. Maybe this is good enough? But it could be that Marginalia does not work with environment variables in candidates. Can that happen?

**Comment by minad** [comment]
What are shadowed paths?

**Comment by minad** [comment]
> Ah I see you match on both the cand and the minibuffer contents.

I have to match on both since the candidates could be full strings as in `consult-recent-file`. The minibuffer contents should be matched to handle `find-file`.

**Comment by clemera** [comment]
If you have already `~/` in you prompt you can continue typing `~//sudo:` for example, the path before `/sudo:` will be ignored.

**Comment by clemera** [comment]
That is how I usually drop into tramp.

**Comment by minad** [comment]
What does this mean? The shadowed part is simply ignored or does it still have some meaning? I just saw that Selectrum grays out that part.

**Comment by clemera** [comment]
Yes it is ignored that is what `substitute-in-file-name` handles, this is built-in for Emacs file completions.

**Comment by minad** [comment]
Okay, I can fix this in the regexp. Seems to be a rather stupid feature honestly, more like a bug turned feature.

**Comment by minad** [comment]
Fixed in e4b3fcd4151af7148e7c82cfe66abedeaa9216aa

**Comment by clemera** [comment]
Hm, I like that feature, use it all the time. Why not just use `substitute-in-file-name` it also handles the env var substitution you mentioned above.

**Comment by minad** [comment]
I am not very fond of this feature. I think it has been introduced due to how the completion ui workssince it just allows you to append to an already existing path. I also added support for `substitute-in-file-name` now. This didn't work before for file annotators btw, since `file-attributes` was called on the path where the env variables were still present.

**Comment by minad** [comment]
See 153417adc9d7779a5393ad37c6584f875291b6ac

**Comment by minad** [comment]
What I want to say regarding the feature - I think it is not bad to have the ability to write such paths as you do, but to me it seems that the substitution is handled on the wrong level. Imho this substitution should simply take place on the ui level and not on the file path handling level below. Some wishful thinking...

**Comment by clemera** [comment]
I see, makes sense, good point with using `substitute-in-file-name` for the file attributes later I overlooked that and thought it wouldn't be necessary.

**Comment by minad** [comment]
Yes, this is what I meant before, that substitute-in-file-name should also be used there if we want to use it after all. It is good now and works well. Thank you for your help!

It seems there are not many people using shadowed paths or env vars in paths. Otherwise we might have seen complaints here before. @oantolin said something about using env variables in as bookmarks if I recall correctly? But he does not seem to be using that anymore otherwise he would have fixed the file annotator to work with his env paths :)

**Comment by clemera** [comment]
Wait, aren't env vars only possible in the path you input? Can they also be in paths of the candidate list at all?

**Comment by minad** [comment]
I don't think they can be in paths of the candidate list, but `marginalia--full-candidate` returns a concatenation of the minibuffer contents and the candidate.

**Comment by oantolin** [comment]
I agree that it would be better to handle these `//` or `/~/` paths at a higher level instead requiring lots of separate functions to call `substitute-in-file-name` themselves. (I've caught several spots in Embark where I needed to add a call to `substitute-in-file-name` but wouldn't swear I found them all!).

And yes I stopped using environment vars as bookmarks for directories, but it actually works pretty well since you can use it both inside and outside emacs: `C-x C-f $ORG/restaurants.org` and `cd $ORG` in the shell.

**Comment by minad** [comment]
> but it actually works pretty well since you can use it both inside and outside emacs: C-x C-f $ORG/restaurants.org and cd $ORG in the shell.

I don't get that, what is outside Emacs? :-P

**Comment by oantolin** [comment]
I barely remember that outside world. 😉 I stopped using environment variable to bookmark directories at the same time I stopped using shells outside Emacs (and for the most part stopped using shells inside Emacs too).

**Comment by minad** [comment]
It is the @protesilaos approach - centering the computing experience around Emacs. It is not bad. I am still missing out EXWM and systemE. I also haven't fully committed yet to the Gnus and Emacs Web Wowser :sweat_smile:

**Comment by skeezix** [comment]
Super awesome teamwork guys! This patch for marginalia solves my problem where Emacs was completely hung when doing /ssh: ..

I've manually clobbered my ~/.emacs.d/elpa/marginalia-0.3 with current master, and look forward to the melpa update down the road.

Very much appreciated guys!

**Comment by protesilaos** [comment]
> It is the @protesilaos approach - centering the computing experience around Emacs. It is not bad. I am still missing out EXWM and systemE. I also haven't fully committed yet to the Gnus and Emacs Web Wowser sweat_smile

Don't know about you, but `M-x tetris` has allowed me to join the club of cool kids with their fancy gaming rigs.

* * *

Thanks for the work you are doing here.  I am really happy with it.

**Pull request closed without merging**
